version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: airport
      POSTGRES_USER: airport
      POSTGRES_PASSWORD: airport
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  pgdata: